<template>
	<v-alert
      border="top"
      :type="msgtype"
      variant="outlined"
      prominent
      v-if="show"
    >{{msg}}</v-alert>
	<form @submit="onSubmit">
	<v-text-field v-model="name"></v-text-field>
	<v-text-field v-model="short"></v-text-field>
	<v-text-field v-model="secret" readonly></v-text-field>
	<v-btn type="submit">Create Mission</v-btn>
	</form>
</template>

<script>
import axios from "axios";
export default {
	data: () => ({
		name: "Give it a name",
		short: "Short description",
		secret: "Will be generated by the server",
		msg: "empty message",
		show: false,
		msgtype: "error"
	}),
	methods: {
		onSubmit(event) {
			event.preventDefault();
			axios.post("/api/create", {
				name: this.name,
				short: this.short
			}, {
				withCredentials:true
			}).then((data) => {
				let secret = data["data"]["secret"];
				localStorage.setItem("secret", secret);
				this.secret = secret;
				this.msg = "Success. Remember your secret '" + secret + "'";
				this.show = true;
				this.msgtype = "success";
			}).catch((e) => {
				this.msg = "Failed: " + e.response.data.error;
				this.show = true;
				this.msgtype = "error";
			});
		}
	}
}
</script>
